### PR TITLE
Export and display list of all credit card features

### PR DESCRIPTION
**Pull request by j7mah**
Files to check/test:
- allCards.php (in src folder): new page to output all the credit cards companies, names and networks
- DBController.php (in src folder): new page to help get query of matched credit card
- submit.php (in src folder): new page to get to allCards.php page and also home to export button

User stories Completed:
1) As a user I want to export my selection results to keep track of my selections  
Tasks Completed: 
- Created button to export information on matched credit card
- Created SQL query to grab information of the matched credit card
- Created PHP function to combine button and query

2) As a user I want to see all the credit cards to see which all the options available 
Tasks Completed: 
- Created hyperlink to a page that displays all the credit cards in the application
- Created SQL query to grab all the information on all the credit cards

What to test:
- allCards.php: Make sure only three columns (credit cards companies, names and networks) are displayed. Tested this on my own local server and it works so far (show the values in a chart). Please check the query is correct and make adjustments if any.
- DBController.php: File helps return the specified information for the matched card. Tested this on my own local server and it works so far (gets the right values for one matched card). Please check the feasibility of this file as I think this could be moved to my_connect.php in the future. 
- submit.php: FIle has the two new features: exporting matched card info into an excel file and display list of all credit card companies, names and networks. Tested both features on my own local server and it works so far (gets the right values for one matched card and link to list works). Please check the feasibility of both files and make adjustments if any. Test the excel function works for various credit card cases. NOTE: IF IT BRINGS UP A FORMATING ERROR BUT ASKS IF YOU WOULD LIKE TO OPEN THE FILE CLICK ON YES AND IT WILL WORK. In addition, the program is only setup to export information on ONE matched credit card. For now since our program only matches one card this is okay but the functionality to include multiple credit cards can be looked into the future once more than one card is matched.

### CODE REVIEW

**Comment by j7mah** [comment]
Just talked to @dylanh107 and he will assist in the review. sorry for spamming everyone with the request

**Comment by dylanh107** [comment]
I've reviewed the pull request on the j7mah MSCI server and there are no issues with functionality. All credit cards are visible on the site and the export to excel function works. As you mentioned in the pull request, there is a lot of potential for improving upon the excel export functionality. Right now, it only exports the one credit card that the users match with. In the future, it would be useful to export more information on a multitude of cards for users, and perhaps improve the visuals for the excel spreadsheet.

**Comment by j7mah** [comment]
@dylanh107 I think you closed it without merging by accident

**Comment by dylanh107** [comment]
Sorry Jason, meant to merge this previously, not close

**Pull request merged**
