### PR TITLE
KnowledgeBase UI Update

### PR DESCRIPTION
**Pull request by dylanh107**
Updated UI for Knowledgebase pages, format is now identical to that of the homepage. Also removed obsolete html files. This update was necessary this sprint to standardize some of our interface formatting, even though it wasn't explicitly stated in our sprint plan.

For testing:
- Ensure that all buttons work properly in the knowledgebase. There are 6 buttons for subpages, and one button to return to homepage.
- For each knowledgebase subpage, there is one button to return to knowledgebase, ensure that these return buttons work properly.

User story addressed:
- As a user I want to learn more about the types of reward programs so I can decide which programs suit my needs

Next steps:
- Actual content of the knowledgebase subpages can be reformatted/redesigned

### CODE REVIEW

**Comment by j7mah** [comment]
@dylanh107 I noticed you deleted the php elements in these files can you please add them back in?

**Comment by dylanh107** [comment]
@j7mah right, just added the php tags back in (had removed them for testing in html). Should be good to go now.

**Comment by j7mah** [comment]
@dylanh107 i think the php tags are still missing for these files typesOfCreditCards, knowledgeBase, howCreditCardsWork, creditCardFess and creditCardCompanies

**Comment by j7mah** [comment]
@dylanh107 can you please fix the formatting of the php instances of the code? i think it has to be on two separate lines. Besides that everything else seems good!

**Comment by dylanh107** [comment]
@j7mah pushed changes, sorry for the delay on this

**Comment by j7mah** [comment]
@dylanh107 I review and test your updates with my local server for the knowledge base section and everything you wanted to test works! Thanks for doing this! I like how the buttons look visually better!

**Pull request merged**
